# Generated by Django 5.2.1 on 2025-05-08 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('posicion', models.CharField(choices=[('base', 'Base'), ('escolta', 'Escolta'), ('alero', 'Alero'), ('ala_pivot', 'Ala-Pívot'), ('pivot', 'Pívot')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('relajado', 'Relajado'), ('intermedio', 'Intermedio'), ('alto', 'Alto')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
