# Generated by Django 5.2.1 on 2025-05-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad_dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('indiferente', 'Indiferente')], max_length=20)),
                ('disponibilidad_horaria', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('todo_dia', 'Todo el día'), ('indiferente', 'Indiferente')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto'), ('indiferente', 'Indiferente')], max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anuncio', to='basketconecta.jugador')),
            ],
        ),
    ]
