# Generated by Django 5.2.1 on 2025-05-08 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0002_anunciojugador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('infantil', 'Infantil'), ('cadete', 'Cadete'), ('juvenil', 'Juvenil'), ('senior', 'Senior'), ('veteranos', 'Veteranos')], max_length=20)),
                ('primera_camiseta', models.CharField(max_length=100)),
                ('primera_pantalon', models.CharField(max_length=100)),
                ('segunda_camiseta', models.CharField(blank=True, max_length=100, null=True)),
                ('segunda_pantalon', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=10)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='equipos', to='basketconecta.jugador')),
            ],
        ),
    ]
