# Generated by Django 5.2.1 on 2025-05-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0003_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_partido', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('indiferente', 'Indiferente')], max_length=15)),
                ('horario_partido', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('todo_dia', 'Todo el día'), ('indiferente', 'Indiferente')], max_length=15)),
                ('direccion_partido', models.CharField(max_length=255)),
                ('dia_entrenamiento', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('indiferente', 'Indiferente')], max_length=15, null=True)),
                ('horario_entrenamiento', models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('todo_dia', 'Todo el día'), ('indiferente', 'Indiferente')], max_length=15, null=True)),
                ('direccion_entrenamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anuncio', to='basketconecta.equipo')),
            ],
        ),
    ]
