# Generated by Django 5.2.1 on 2025-05-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0004_anuncioequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto_jugador',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
    ]
