# Generated by Django 5.2.1 on 2025-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0009_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
