# Generated by Django 5.2.1 on 2025-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0010_equipo_latitud_equipo_longitud_jugador_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='longitud',
        ),
        migrations.AddField(
            model_name='anuncioequipo',
            name='latitud_entrenamiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioequipo',
            name='latitud_partido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioequipo',
            name='longitud_entrenamiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioequipo',
            name='longitud_partido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
