# Generated by Django 5.2.1 on 2025-05-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0010_chat_anuncio_fields'),
        ('basketconecta', '0011_remove_equipo_latitud_remove_equipo_longitud_and_more'),
    ]

    operations = [
    ]
