# Generated by Django 5.2.1 on 2025-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0012_merge_20250530_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('jugador', 'equipo', 'anuncio_jugador', 'anuncio_equipo')},
        ),
    ]
