# Generated by Django 5.2.1 on 2025-06-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0013_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitacion',
            unique_together=set(),
        ),
    ]
