# Generated by Django 5.2.1 on 2025-06-08 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketconecta', '0015_chatequipo_mensajechatequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
